url:
baseurl:
title: AALT
permalink: /:categories/:year/:month/:day/:title:output_ext
BASE_PATH :

post_limit:

author : 
  name : AALT
  site: https://aalt.org
  description : Afro-Latin American Literature in translation es un proyecto de promoción y traducción de obras afrolatinoamericanas
  image : avatar.png
  email : proyectomorel@gmail.com
  github : 
  twitter : 
  instagram: 


#Collections
collections:
  cities:
    output: true
    permalink: /ciudades/:name
  books:
    output: true
    permalink: /obras/:name
  authors:
    output: true
    permalink: /autoras/:name
  publishers:
    output: true
    permalink: /imprentas-y-editoriales/:name
  repositories:
    output: true
    permalink: /repositorios/:name
  periods:
    output: true 
    permalink: /periodos/:name